---
# nova compute
- name: compute process check
  sensu_process_check: service=nova-compute
  notify: restart sensu-client

- name: neutron linuxbridge agent check
  sensu_process_check: service=neutron-linuxbridge-agent
  notify: restart sensu-client
  when: neutron.plugin=='ml2'

- name: nova cinder session check
  sensu_metrics_check: name=check-cinder-sessions plugin=check-cinder-sessions.py
                       interval=10
  notify: restart sensu-client
  when: "'rbd_volumes' not in cinder.enabled_backends"
